version: '3'
services:
  plexamp:
    container_name: plexamp
    network_mode: host  # brigde mode seems not working
    privileged: true
    image: plexamp:latest  # build this image first with Dokerfile in this repo
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./config:/root/.local/share/Plexamp/Settings # replace that with the appropriate host binding
    environment:
      - PLEXAMP_CLAIM_TOKEN=xxxxxxxx # get your claim at https://www.plex.tv/claim/. Note the token EXPIRES in 4 minutes
      - PLEXAMP_PLAYER_NAME=docker # replace this with your player name
    restart: always
