name: Deploy Images to GHCR

on:
  push:
    branches:
      - docker
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Plexamp Image"
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t ghcr.io/${{github.actor}}/plexamp:latest --load .
          docker push ghcr.io/${{github.actor}}/plexamp:latest
