name: Deploy Images to GHCR

on:
  push:
    branches:
      - docker
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,arm"

      - uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Plexamp Image"
        run: |
          docker build -f Dockerfile-arm64v8 . --tag ghcr.io/${{github.actor}}/plexamp:arm64v8
          docker push ghcr.io/${{github.actor}}/plexamp:arm64v8
